version: '3.8'

volumes:
  data:

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USERNAME=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
